### ISSUE TITLE
[AVM Question/Feedback]:  Feedback on readme restructure

### ISSUE THREAD

**Issue by sourav-azms** [Azure/terraform-azurerm-avm-res-network-dnsresolver#23]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

1. Can we just mentioned the terraform registry link that has been refer while writing the module, under Resource section in readme file,
like, 
[azurerm_private_dns_resolver_inbound_endpoint] (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_dns_resolver_inbound_endpoint)

[azurerm_private_dns_resolver_outbound_endpoint] (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_dns_resolver_outbound_endpoint)

2. Might be a section for usage and guidance or additional information in the readme, about the product would be beneficial ?
3. Can we also attach the Microsoft public documentation link for the product in the readme file.

**Comment by humanascode** [comment]
Thank you @sourav-azms I will look into it

**Comment by humanascode** [comment]
Hi @sourav-azms Thanks for your feedback. We already have these links in the readme file. I am going to go ahead and close this issue. If you have any further feedback, please feel free to raise another issue.
