### ISSUE TITLE
[AVM Module Issue]: Typo, "deafult" should be "default"

### ISSUE THREAD

**Issue by pieter-jangoeman** [Azure/terraform-azurerm-avm-res-network-dnsresolver#64]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

On lines 64 and 68, there's typo's in the word "default"

**Comment by humanascode** [comment]
Thank you for your feedback @pieter-jangoeman ! The issue has been fixed in version 0.3.0

**Comment by pieter-jangoeman** [comment]
Welcome!

Op wo 9 okt 2024 om 14:10 schreef Itamar ***@***.***>:
